In [1]:
import pandas as pd

In [2]:
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)
df_ratings = pd.read_csv('IMDb ratings.csv')

In [3]:
# select columns
df_movies = df_movies[['imdb_title_id', 'title', 'year',
                       'genre', 'country']]

df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

# merge()

In [11]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'] , 'age': [30, 23, 25, 22]})

In [10]:
df2 = pd.DataFrame({'id': ['C', 'D', 'E', 'F'] , 'job': ['Doctor', 'Statistician','Accountant', 'Developer']})

In [13]:
df1.merge(df2, on = 'id', how='inner')

  id  age           job
0  C   25        Doctor
1  D   22  Statistician

In [15]:
pd.merge(df1, df2, on = 'id', how='inner')

  id  age           job
0  C   25        Doctor
1  D   22  Statistician

## Inner join

### Exercise

In [18]:
# merge df_movies and df_ratings (inner join) 2ways
df_movies.merge(df_ratings, on = 'imdb_title_id', how='inner')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [22]:
pd.merge(df_ratings, df_movies, on = 'imdb_title_id', how='inner')

,imdb_title_id,total_votes,mean_vote,title,year,genre,country
0,tt0000009,154,5.9,Miss Jerry,1894,Romance,USA
1,tt0000574,589,6.3,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,188,6.0,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,446,5.3,Cleopatra,1912,"Drama, History",USA
4,tt0002130,2237,6.9,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...,...,...
85850,tt9908390,398,5.5,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,724,7.9,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,265,7.8,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,194,9.4,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,102,6.8,La vida sense la Sara Amat,2019,Drama,Spain

## Outer join (Full join)

### Exercise

In [23]:
# merge df_movies and df_ratings (outer join)
pd.merge(df_ratings, df_movies, on = 'imdb_title_id', how='outer')

,imdb_title_id,total_votes,mean_vote,title,year,genre,country
0,tt0000009,154,5.9,Miss Jerry,1894,Romance,USA
1,tt0000574,589,6.3,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,188,6.0,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,446,5.3,Cleopatra,1912,"Drama, History",USA
4,tt0002130,2237,6.9,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...,...,...
85850,tt9908390,398,5.5,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,724,7.9,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,265,7.8,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,194,9.4,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,102,6.8,La vida sense la Sara Amat,2019,Drama,Spain

## Exclusive Outer join (Exclusive Full join)

In [27]:
# indicator=True
pd.merge(df1, df2, on = 'id', how='outer', indicator=True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [31]:
# query
df = pd.merge(df1, df2, on = 'id', how='outer', indicator=True).query("_merge == 'left_only' or _merge == 'right_only'")

In [32]:
# shape
df.shape

(4, 4)

In [34]:
df1.shape

(4, 2)

In [35]:
df2.shape

(4, 2)

### Exercise

In [37]:
# merge df_movies and df_ratings
pd.merge(df_movies,df_ratings, on = 'imdb_title_id', how='outer', indicator=True)

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9,both
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3,both
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0,both
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3,both
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9,both
...,...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5,both
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9,both
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8,both
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4,both
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8,both

##  Left join

In [38]:
df1.merge(df2, on = 'id', how = 'left', indicator=True)

  id  age           job     _merge
0  A   30           NaN  left_only
1  B   23           NaN  left_only
2  C   25        Doctor       both
3  D   22  Statistician       both

### Exercise

In [40]:
# extract a 50% sample of the df_movies dataframe
df = df_movies.sample(frac = 0.5)

In [46]:
# merge df_movies_sample and df_ratings (left join)
hd = pd.merge(df, df_ratings, on = 'imdb_title_id', how='left')

In [43]:
# shape
df.shape

(42928, 5)

In [47]:
hd.shape

(42928, 7)

In [45]:
df_ratings.shape

(85855, 3)

## Exclusive Left join

In [51]:
# indicator=True
pd.merge(df1, df2, on = 'id', how='left',indicator=True)

  id  age           job     _merge
0  A   30           NaN  left_only
1  B   23           NaN  left_only
2  C   25        Doctor       both
3  D   22  Statistician       both

In [53]:
# query
pd.merge(df1, df2, on = 'id', how='left',indicator=True).query("_merge == 'left_only'")

  id  age  job     _merge
0  A   30  NaN  left_only
1  B   23  NaN  left_only

### Exercise

In [55]:
# make a copy of the df_movies dataframe
df = df_movies.copy()

In [59]:
# set the first 1000 values of 'imdb_title_id' column as 'tt1234567890'
for i in df.index:
    if i < 1000:
        df.loc[i, 'imdb_title_id'] = 'tt1234567890'

In [60]:
df

,imdb_title_id,title,year,genre,country
0,tt1234567890,Miss Jerry,1894,Romance,USA
1,tt1234567890,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt1234567890,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt1234567890,Cleopatra,1912,"Drama, History",USA
4,tt1234567890,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [63]:
# merge df_movies_2 and df_ratings (exclusive left join)
hd = df.merge(df_ratings, on = 'imdb_title_id', how='left',indicator=True).query("_merge == 'left_only'")

In [64]:
# shape
hd.shape

(1000, 8)

In [66]:
df.shape

(85855, 5)

In [67]:
df_ratings.shape

(85855, 3)

## Right join

### Exercise

In [69]:

# extract a 30% sample of the df_ratings dataframe
df = df_ratings.sample(frac = 0.3)

In [71]:
# merge df_movies and df_ratings_sample (right join)
hd = df.merge(df_movies, on='imdb_title_id', how='right')

In [72]:
# shape
hd.shape

(85855, 7)

In [74]:
df.shape

(25756, 3)

In [75]:
df_movies.shape

(85855, 5)

## Exclusive Right join

In [76]:
# indicator=True
df.merge(df_movies, on='imdb_title_id', how='right', indicator=True)

,imdb_title_id,total_votes,mean_vote,title,year,genre,country,_merge
0,tt0000009,NaN,NaN,Miss Jerry,1894,Romance,USA,right_only
1,tt0000574,NaN,NaN,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,right_only
2,tt0001892,NaN,NaN,Den sorte drøm,1911,Drama,"Germany, Denmark",right_only
3,tt0002101,446.0,5.3,Cleopatra,1912,"Drama, History",USA,both
4,tt0002130,NaN,NaN,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,right_only
...,...,...,...,...,...,...,...,...
85850,tt9908390,NaN,NaN,Le lion,2020,Comedy,"France, Belgium",right_only
85851,tt9911196,NaN,NaN,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,right_only
85852,tt9911774,NaN,NaN,Padmavyuhathile Abhimanyu,2019,Drama,India,right_only
85853,tt9914286,NaN,NaN,Sokagin Çocuklari,2019,"Drama, Family",Turkey,right_only
85854,tt9914942,NaN,NaN,La vida sense la Sara Amat,2019,Drama,Spain,right_only

In [77]:
# query
df.merge(df_movies, on='imdb_title_id', how='right', indicator=True).query('_merge == "right_only"')

,imdb_title_id,total_votes,mean_vote,title,year,genre,country,_merge
0,tt0000009,NaN,NaN,Miss Jerry,1894,Romance,USA,right_only
1,tt0000574,NaN,NaN,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,right_only
2,tt0001892,NaN,NaN,Den sorte drøm,1911,Drama,"Germany, Denmark",right_only
4,tt0002130,NaN,NaN,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,right_only
5,tt0002199,NaN,NaN,"From the Manger to the Cross; or, Jesus of Naz...",1912,"Biography, Drama",USA,right_only
...,...,...,...,...,...,...,...,...
85850,tt9908390,NaN,NaN,Le lion,2020,Comedy,"France, Belgium",right_only
85851,tt9911196,NaN,NaN,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,right_only
85852,tt9911774,NaN,NaN,Padmavyuhathile Abhimanyu,2019,Drama,India,right_only
85853,tt9914286,NaN,NaN,Sokagin Çocuklari,2019,"Drama, Family",Turkey,right_only
85854,tt9914942,NaN,NaN,La vida sense la Sara Amat,2019,Drama,Spain,right_only

### Exercise

In [78]:
# make a copy of the df_ratings dataframe
df = df_ratings.copy()

In [80]:
df

      imdb_title_id  total_votes  mean_vote
0         tt0000009          154        5.9
1         tt0000574          589        6.3
2         tt0001892          188        6.0
3         tt0002101          446        5.3
4         tt0002130         2237        6.9
...             ...          ...        ...
85850     tt9908390          398        5.5
85851     tt9911196          724        7.9
85852     tt9911774          265        7.8
85853     tt9914286          194        9.4
85854     tt9914942          102        6.8

[85855 rows x 3 columns]

In [88]:
# set the first 1000 values of 'imdb_title_id' column as 'tt1234567890'
for i in df.index:
    if i < 1000:
        df.loc[i, 'imdb_title_id'] = 'tt1234567890'

In [89]:
df

      imdb_title_id  total_votes  mean_vote \timdb_title_id
0      tt1234567890          154        5.9    tt1234567890
1      tt1234567890          589        6.3    tt1234567890
2      tt1234567890          188        6.0    tt1234567890
3      tt1234567890          446        5.3    tt1234567890
4      tt1234567890         2237        6.9    tt1234567890
...             ...          ...        ...             ...
85850     tt9908390          398        5.5             NaN
85851     tt9911196          724        7.9             NaN
85852     tt9911774          265        7.8             NaN
85853     tt9914286          194        9.4             NaN
85854     tt9914942          102        6.8             NaN

[85855 rows x 4 columns]

In [93]:
# merge df_movies and df_ratings_2 (exclusive right join)
hd = df.merge(df_movies, on='imdb_title_id', how='outer', indicator=True).query('_merge == "right_only"')

In [92]:
# shape
df.shape

(85855, 4)

In [94]:
hd.shape

(1000, 9)

In [96]:
df_movies.shape

(85855, 5)